"use client";

import { useMemo, useState } from "react";
import JSZip from "jszip";
import { CheckCircle2, Download, Monitor, Smartphone, XCircle } from "lucide-react";
import { Badge, Button } from "@/components/ui";
import { buildPreviewDoc } from "@/lib/assemble";
import { cn } from "@/lib/utils";
import { toast } from "@/components/ui";

export interface PreviewFiles {
  html: string;
  css: string;
  js: string;
}

interface Props {
  projectName: string;
  files: PreviewFiles;
  logo: { mime: string; dataUrl: string } | null;
  references: { mime: string; dataUrl: string }[];
  checks?: { name: string; pass: boolean }[];
  qa?: { score: number; issues: string[] } | null;
}

type Tab = "preview" | "html" | "css" | "js" | "report";

function extFor(mime: string): string {
  if (mime.includes("svg")) return ".svg";
  if (mime.includes("png")) return ".png";
  if (mime.includes("webp")) return ".webp";
  return ".jpg";
}

export function SitePreview({ projectName, files, logo, references, checks, qa }: Props) {
  const [tab, setTab] = useState<Tab>("preview");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const doc = useMemo(() => buildPreviewDoc(files), [files]);

  const exportZip = async () => {
    const zip = new JSZip();
    zip.file("index.html", files.html);
    zip.file("styles.css", files.css);
    zip.file("script.js", files.js);
    const assets = zip.folder("assets")!;
    if (logo?.dataUrl) assets.file(`logo${extFor(logo.mime)}`, logo.dataUrl.split(",")[1] ?? "", { base64: true });
    references.forEach((r, i) => {
      assets.file(`reference-${i + 1}${extFor(r.mime)}`, r.dataUrl.split(",")[1] ?? "", { base64: true });
    });
    assets.file(
      "README.md",
      `# ${projectName} — generated by AlephVisio Studio\n\nSelf-contained site: open index.html in any browser.\nstyles.css + script.js are referenced from index.html.\n`,
    );
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-site.zip`;
    a.click();
    URL.revokeObjectURL(url);
    toast("ok", "ZIP exported — index.html, styles.css, script.js, assets/");
  };

  const tabs: { id: Tab; label: string }[] = [
    { id: "preview", label: "Preview" },
    { id: "html", label: "index.html" },
    { id: "css", label: "styles.css" },
    { id: "js", label: "script.js" },
    { id: "report", label: "QA report" },
  ];

  return (
    <div className="overflow-hidden rounded-xl border border-ink-700 bg-ink-900">
      <div className="flex flex-wrap items-center gap-2 border-b border-ink-700 px-3 py-2">
        {tabs.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={cn(
              "rounded-md px-2.5 py-1 font-mono text-[11px] font-semibold transition",
              tab === t.id ? "bg-ink-700 text-teal-300" : "text-mist-500 hover:text-mist-100",
            )}
          >
            {t.label}
          </button>
        ))}
        <div className="ml-auto flex items-center gap-1.5">
          {tab === "preview" && (
            <div className="mr-1 flex overflow-hidden rounded-md border border-ink-600">
              <button
                onClick={() => setDevice("desktop")}
                aria-label="Desktop preview"
                className={cn("px-2 py-1", device === "desktop" ? "bg-ink-700 text-teal-300" : "text-mist-500")}
              >
                <Monitor size={13} />
              </button>
              <button
                onClick={() => setDevice("mobile")}
                aria-label="Mobile preview"
                className={cn("px-2 py-1", device === "mobile" ? "bg-ink-700 text-teal-300" : "text-mist-500")}
              >
                <Smartphone size={13} />
              </button>
            </div>
          )}
          <Button variant="outline" className="px-2.5 py-1.5 text-xs" onClick={() => void exportZip()}>
            <Download size={13} /> Export ZIP
          </Button>
        </div>
      </div>

      {tab === "preview" && (
        <div className="flex justify-center bg-ink-950 p-3">
          <iframe
            title="Generated website preview"
            sandbox="allow-scripts"
            srcDoc={doc}
            className={cn(
              "h-[560px] rounded-lg border border-ink-700 bg-white transition-all",
              device === "mobile" ? "w-[390px]" : "w-full",
            )}
          />
        </div>
      )}

      {(tab === "html" || tab === "css" || tab === "js") && (
        <pre className="slim-scroll max-h-[560px] overflow-auto bg-ink-950 p-4 font-mono text-[11.5px] leading-relaxed text-mist-300">
          <code>{tab === "html" ? files.html : tab === "css" ? files.css : files.js}</code>
        </pre>
      )}

      {tab === "report" && (
        <div className="max-h-[560px] overflow-auto p-5">
          <div className="mb-4 flex items-center gap-3">
            {qa && (
              <Badge tone={qa.score >= 80 ? "ok" : qa.score >= 60 ? "warn" : "error"}>
                visual QA score {qa.score}/100
              </Badge>
            )}
            {checks && (
              <Badge tone={checks.every((c) => c.pass) ? "ok" : "warn"}>
                {checks.filter((c) => c.pass).length}/{checks.length} checks green
              </Badge>
            )}
          </div>
          {qa && qa.issues.length > 0 && (
            <div className="mb-4 rounded-lg border border-ink-700 bg-ink-850 p-3 text-xs text-mist-300">
              <p className="mb-1 font-bold uppercase tracking-wider text-mist-500">QA findings</p>
              <ul className="list-inside list-disc space-y-0.5">
                {qa.issues.map((issue, i) => (
                  <li key={i}>{issue}</li>
                ))}
              </ul>
            </div>
          )}
          <ul className="grid gap-1.5">
            {(checks ?? []).map((c) => (
              <li key={c.name} className="flex items-center gap-2 text-sm">
                {c.pass ? <CheckCircle2 size={15} className="text-forest-400" /> : <XCircle size={15} className="text-ember-400" />}
                <span className={c.pass ? "text-mist-100" : "text-ember-400"}>{c.name}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
